# Use Node.js 18 Alpine as base image
FROM node:18-alpine

# Set working directory inside container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install



# Copy the rest of the application code
COPY . .

# Expose port 3000
EXPOSE 3000

# Command to run the server
CMD ["npm", "start"]
